[tool.poetry]
name = "scintill-ai"
version = "0.1.0"
description = ""
authors = ["Vincenzo <vincenzo.ventriglia@outlook.com>"]
readme = "README.md"
packages = [{include = "scintill_ai"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
numpy = "1.26.4"
matplotlib = "^3.9.2"
plotly = "^5.24.1"
scikit-learn = "^1.5.2"
pvlib = "^0.11.1"
black = "^24.8.0"
jupyter = "^1.0.0"
python-dotenv = "^1.0.1"
netcdf4 = "^1.7.2"
aiohttp = "^3.11.12"
statsforecast = "^2.0.0"
statsmodels = "^0.14.4"
mapie = "^0.9.2"
shap = "^0.46.0"
ordpy = "^1.1.5"
catboost = "^1.2.7"
conformal-tights = "^0.4.0"
taipy = "^4.0.2"
neuralforecast = "^3.0.0"
vmdpy = "^0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
